#baseURL = "https://christ-blog.nerdworks.dev"
baseURL = ""
title = "On Christianity, theology and philosophy"
theme = "anubis"
enableRobotsTXT = true

[params]
  author = "Raj Vengalil" # You can also set author in post front matter individually

  description = "Thoughts on Christianity, theology and philosophy"
  dateFormat = "02-Jan-2006"
  paginationSinglePost = true
  style = "auto"
  readMore = false

  customCSS = ["css/custom.css"] 

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets in Markdown content
